port=0                                              # Disable DNS server
dhcp-range=10.10.67.80,10.10.67.100,12h                  # DHCP range
dhcp-option=3,10.10.67.1                              # Default ACTIVE_GW
dhcp-option=6,8.8.8.8,10.10.67.1,1.1.1.1              # DNS servers
dhcp-option=66,10.10.67.52                             # (optional but helps strict UEFI firmware)
server=8.8.8.8
enable-tftp
tftp-root=/tftp

# Match UEFI first
dhcp-match=set:uefi,option:client-arch,7
dhcp-match=set:uefi,option:client-arch,9
dhcp-match=set:uefi,option:client-arch,11
dhcp-match=set:uefi,option:client-arch,15

# UEFI boot
dhcp-boot=tag:uefi,efi/boot/bootx64.efi

# Default BIOS fallback
dhcp-boot=bios/pxelinux.0,pxeserver,10.10.67.52

# PXE stability
dhcp-no-override

# ignore client-id changes
dhcp-authoritative
dhcp-ignore-clid
# Log DHCP requests for debugging
log-dhcp
